server:
  port: 88


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-gateway
  gateway:
    routes:
      - id: host_route
        uri: https://www.baidu.com
        predicates:
          - Query=baidu

